imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    lock: 'redis://redis'
    esi: { enabled: true }
    fragments:
        enabled: true
        path: /_fragment


# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false

fos_http_cache:
    proxy_client:
        symfony:
                        # for single server installations:
            use_kernel_dispatcher: true
            #http:
            #    servers:
            #    - 123.123.123.1:6060
            #    - 123.123.123.2
             #   base_url: yourwebsite.com
    cache_control:
        defaults:
            overwrite: true
        rules:
        -
            match:
                path: ^/foshttp$
            headers:
                cache_control: { public: true, max_age: 10, s_maxage: 10 }
                etag: true
                vary: [Accept-Encoding, Accept-Language]
    invalidation:
        enabled: true    # Defaults to 'auto'
        rules:
        - match:
              attributes:
                  _route: "editPosts"
          routes:
              show: ~
              list:
                  ignore_extra_params: false    # Defaults to true

